name: Release Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  release-windows:
    runs-on: windows-latest  # Menggunakan Windows runner
    strategy:
      matrix:
        electron-arch: [x64, ia32]  # Membangun untuk arsitektur 64-bit dan 32-bit
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install
        run: |
          Remove-Item -Recurse -Force node_modules
          Remove-Item -Force package-lock.json -ErrorAction SilentlyContinue
          npm install

      - name: Build app
        run: npm run build

      - name: Build Windows installer
        run: npx electron-builder --win --${{ matrix.electron-arch }} --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: quickrun-studio-windows-${{ matrix.electron-arch }}
          path: |
            dist/*.exe
            dist/*.blockmap
            dist/*.yml